export const dataAsArray = [
  {
    "id": 1,
    "name": "Zapatillas Deportivas",
    "brandName": "Marca Fitness",
    "description": "Zapatillas ideales para entrenamientos intensivos.",
    "price": 89.99,
    "image": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw57f02c7c/images/a_107/A04523C_A_107X1.jpg?sw=964",
    "stock": 25,
    "waist": 9,
    "color": "Negro y Rojo",
    "material": "Malla transpirable",
    "sold": 15,
    "status": "active"
  },
  {
    "id": 2,
    "name": "Zapatillas para Correr",
    "brandName": "Running Co.",
    "description": "Diseñadas para corredores que buscan comodidad y rendimiento.",
    "price": 99.5,
    "image": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dwd42eb113/images/a_107/A05436C_A_107X1.jpg?sw=964",
    "stock": 20,
    "waist": 8,
    "color": "Azul y Blanco",
    "material": "Tejido ligero",
    "sold": 10,
    "status": "active"
  },
  {
    "id": 3,
    "name": "Zapatillas Casuales",
    "brandName": "Urban Style",
    "description": "Estilo urbano y comodidad para el día a día.",
    "price": 79.0,
    "image": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw7f66278d/images/a_107/A05223C_A_107X1.jpg?sw=964",
    "stock": 35,
    "waist": 7,
    "color": "Gris",
    "material": "Lona resistente",
    "sold": 5,
    "status": "active"
  },
  {
    "id": 4,
    "name": "Zapatillas de Skate",
    "brandName": "Skate Zone",
    "description": "Perfectas para los amantes del skateboarding.",
    "price": 74.99,
    "image": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dwf5a9028a/images/a_107/A04482C_A_107X1.jpg?sw=964",
    "stock": 15,
    "waist": 8,
    "color": "Negro",
    "material": "Piel sintética reforzada",
    "sold": 8,
    "status": "active"
  },
  {
    "id": 5,
    "name": "Zapatillas de Entrenamiento",
    "brandName": "Fitness Pro",
    "description": "Optimizadas para ejercicios de fuerza y resistencia.",
    "price": 69.95,
    "image": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw2087ba28/images/a_107/A04522C_A_107X1.jpg?sw=964",
    "stock": 28,
    "waist": 9,
    "color": "Negro y Verde",
    "material": "Materiales resistentes",
    "sold": 12,
    "status": "active"
  }
];