export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const FILTROS_AND_PAGINATION = 'FILTROS_AND_PAGINATION';
export const GET_BY_ID = "GET_BY_ID";
export const GET_PRODUCTS_BY_NAME = "GET_PRODUCTS_BY_NAME"
export const CLEAR_DETAIL= "CLEAR_DETAIL"
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const SORT_PRICE = 'SORT_PRICE';
export const USER = 'USER';
export const GET_CART = 'GET_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const GET_FAVORITES = 'GET_FAVORITES';
export const RESET = "RESET";
